### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by doubledrat** [rene-d/netatmo#15]
> netatmo list
Traceback (most recent call last):
  File "/usr/local/bin/netatmo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/netatmo/netatmo.py", line 929, in main
    args.func(args)
  File "/usr/local/lib/python3.4/dist-packages/netatmo/netatmo.py", line 778, in list_stations
    ws.get_data("*")
  File "/usr/local/lib/python3.4/dist-packages/netatmo/netatmo.py", line 310, in get_data
    auth_token = self.access_token
  File "/usr/local/lib/python3.4/dist-packages/netatmo/netatmo.py", line 265, in access_token
    resp = post_request(_AUTH_REQ, post_params)
  File "/usr/local/lib/python3.4/dist-packages/netatmo/netatmo.py", line 103, in post_request
    ret = json.loads(resp.content)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by rene-d** [comment]
You are running Python 3.4 and this package requires Python 3.5+
